### ISSUE TITLE
How about making an npm package based on this example?

### ISSUE THREAD

**Issue by piglovesyou** [andycmaj/nextjs-passport-session-auth#4]
First, let me say this is the most outstanding example of integrating the passport ecosystem. I think the main idea of it is very general-purpose and many people will get benefits from it. How about creating an npm package for easier integration to Next.js projects?

Plus, I got some ideas to improve it. If you don't mind, can I try to create it based on your example?

* I'd like to turn the `httpOnly` of cookies on, so we can't use `next-cookies`, parsing `document.cookie` on client-side.
* User resolution on client-side could be achieved by `__NEXT_DATA__`

**Comment by piglovesyou** [comment]
Never mind, I created [an express-specific middleware composer](https://github.com/piglovesyou/flow-middleware#readme). I inspired it from you, thank you!

**Comment by andycmaj** [comment]
@piglovesyou be my guest... happy to help. feel free to clone and do whatever you like... :)
